#Official settings for this plugin.
plugin:
  # Translations list of supported locales below
  # https://github.com/EncryptSL/CreditLite/blob/main/src/main/kotlin/com/github/encryptsl/credit/common/config/Locales.kt
  translation: CS
  # Plugin prefix
  prefix: "<#64646F>[<#F9AD47>Credits<#64646F>]</#64646F>"

economy:
  currency_format: '<credits>'
  # This amount is granted to players who don't have an existing account in the database.
  starting_balance: 30
  # Convert large currency values into a more compact format.
  compact_display: false
  # Enable logging about economies activities add, set, withdraw, pay money.
  # Command /eco monolog [player]
  monolog_activity: true

formatting:
  # Currency value format
  currency_pattern: "#,##0.00"
  # Compact value format
  compacted_pattern: "#,##0.0##"
  # Locale symbol format
  currency_locale: en-US

# These settings toggle messages.
messages:
  global:
    notify_add: true
    notify_withdraw: true
    notify_set: true
  target:
    notify_add: true
    notify_withdraw: true
    notify_set: true

# Settings for Database or SQLite connection.
database:
  # For SQLite, the path to the SQLite database file: jdbc:sqlite:plugins/CreditLite/database.db
  # For MySQL, the JDBC connection URL in the format: jdbc:mysql://your_host:port/name_of_database
  connection:
    # Settings for JDBC_HOST
    jdbc_url: "jdbc:sqlite:plugins/CreditLite/database.db"
    # The username of the user to connect to your database (MySQL only).
    username: user_name
    # The password of the user to connect to your database (MySQL only).
    password: password

  # You can enable sql-plugin-logger for some problems with database...
  sql-plugin-logger: false

# Please don't remove this version settings
version: 1.0.1